# Generated by Django 4.0.3 on 2022-04-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('order',)},
        ),
    ]
